<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RRHH.Application\RRHH.Application.csproj" />
    <ProjectReference Include="..\RRHH.Domain\RRHH.Domain.csproj" />
  </ItemGroup>

</Project>
