<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RRHH.Contratos\RRHH.Contratos.csproj" />
    <ProjectReference Include="..\RRHH.Domain\RRHH.Domain.csproj" />
  </ItemGroup>

</Project>
