<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.MTP" Version="10.1.0" />
    <PackageReference Include="NetArchTest.Rules" Version="1.3.2" />
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\RRHH.Api\RRHH.Api.csproj" />
    <ProjectReference Include="..\..\src\RRHH.Application\RRHH.Application.csproj" />
    <ProjectReference Include="..\..\src\RRHH.Contratos\RRHH.Contratos.csproj" />
    <ProjectReference Include="..\..\src\RRHH.Domain\RRHH.Domain.csproj" />
    <ProjectReference Include="..\..\src\RRHH.Infrastructure\RRHH.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\RRHH.Web\RRHH.Web.csproj" />
  </ItemGroup>

</Project>
