// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RRHH.Infrastructure.Datos;

#nullable disable

namespace RRHH.Infrastructure.Datos.Migraciones
{
    [DbContext(typeof(RrhhDbContext))]
    [Migration("20260930043025_Inicial")]
    partial class Inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RRHH.Domain.Entidades.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Colaborador");

                    b.HasIndex("Correo")
                        .IsUnique()
                        .HasDatabaseName("UQ_Colaborador_Correo");

                    b.ToTable("Colaborador", (string)null);
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Departamento");

                    b.HasIndex("PaisId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Departamento_PaisId_Nombre");

                    b.ToTable("Departamento", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Guatemala",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "El Progreso",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Sacatepéquez",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 4,
                            Nombre = "Chimaltenango",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 5,
                            Nombre = "Escuintla",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 6,
                            Nombre = "Santa Rosa",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 7,
                            Nombre = "Sololá",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 8,
                            Nombre = "Totonicapán",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 9,
                            Nombre = "Quetzaltenango",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 10,
                            Nombre = "Suchitepéquez",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 11,
                            Nombre = "Retalhuleu",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 12,
                            Nombre = "San Marcos",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 13,
                            Nombre = "Huehuetenango",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 14,
                            Nombre = "Quiché",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 15,
                            Nombre = "Baja Verapaz",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 16,
                            Nombre = "Alta Verapaz",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 17,
                            Nombre = "Petén",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 18,
                            Nombre = "Izabal",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 19,
                            Nombre = "Zacapa",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 20,
                            Nombre = "Chiquimula",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 21,
                            Nombre = "Jalapa",
                            PaisId = 1
                        },
                        new
                        {
                            Id = 22,
                            Nombre = "Jutiapa",
                            PaisId = 1
                        });
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Empresa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("NombreComercial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Empresa");

                    b.HasIndex("MunicipioId");

                    b.HasIndex("Nit")
                        .HasDatabaseName("IX_Empresa_Nit");

                    b.ToTable("Empresa", (string)null);
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.EmpresaColaborador", b =>
                {
                    b.Property<int>("EmpresaId")
                        .HasColumnType("int");

                    b.Property<int>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaIngreso")
                        .HasColumnType("date");

                    b.Property<string>("Puesto")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmpresaId", "ColaboradorId")
                        .HasName("PK_EmpresaColaborador");

                    b.HasIndex("ColaboradorId");

                    b.ToTable("EmpresaColaborador", (string)null);
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK_Municipio");

                    b.HasIndex("DepartamentoId", "Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Municipio_DepartamentoId_Nombre");

                    b.ToTable("Municipio", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartamentoId = 1,
                            Nombre = "Guatemala"
                        },
                        new
                        {
                            Id = 2,
                            DepartamentoId = 2,
                            Nombre = "Guastatoya"
                        },
                        new
                        {
                            Id = 3,
                            DepartamentoId = 3,
                            Nombre = "Antigua Guatemala"
                        },
                        new
                        {
                            Id = 4,
                            DepartamentoId = 4,
                            Nombre = "Chimaltenango"
                        },
                        new
                        {
                            Id = 5,
                            DepartamentoId = 5,
                            Nombre = "Escuintla"
                        },
                        new
                        {
                            Id = 6,
                            DepartamentoId = 6,
                            Nombre = "Cuilapa"
                        },
                        new
                        {
                            Id = 7,
                            DepartamentoId = 7,
                            Nombre = "Sololá"
                        },
                        new
                        {
                            Id = 8,
                            DepartamentoId = 8,
                            Nombre = "Totonicapán"
                        },
                        new
                        {
                            Id = 9,
                            DepartamentoId = 9,
                            Nombre = "Quetzaltenango"
                        },
                        new
                        {
                            Id = 10,
                            DepartamentoId = 10,
                            Nombre = "Mazatenango"
                        },
                        new
                        {
                            Id = 11,
                            DepartamentoId = 11,
                            Nombre = "Retalhuleu"
                        },
                        new
                        {
                            Id = 12,
                            DepartamentoId = 12,
                            Nombre = "San Marcos"
                        },
                        new
                        {
                            Id = 13,
                            DepartamentoId = 13,
                            Nombre = "Huehuetenango"
                        },
                        new
                        {
                            Id = 14,
                            DepartamentoId = 14,
                            Nombre = "Santa Cruz del Quiché"
                        },
                        new
                        {
                            Id = 15,
                            DepartamentoId = 15,
                            Nombre = "Salamá"
                        },
                        new
                        {
                            Id = 16,
                            DepartamentoId = 16,
                            Nombre = "Cobán"
                        },
                        new
                        {
                            Id = 17,
                            DepartamentoId = 17,
                            Nombre = "Flores"
                        },
                        new
                        {
                            Id = 18,
                            DepartamentoId = 18,
                            Nombre = "Puerto Barrios"
                        },
                        new
                        {
                            Id = 19,
                            DepartamentoId = 19,
                            Nombre = "Zacapa"
                        },
                        new
                        {
                            Id = 20,
                            DepartamentoId = 20,
                            Nombre = "Chiquimula"
                        },
                        new
                        {
                            Id = 21,
                            DepartamentoId = 21,
                            Nombre = "Jalapa"
                        },
                        new
                        {
                            Id = 22,
                            DepartamentoId = 22,
                            Nombre = "Jutiapa"
                        });
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoIso2")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nchar(2)")
                        .IsFixedLength();

                    b.Property<int>("EdadMaxima")
                        .HasColumnType("int");

                    b.Property<int>("EdadMinima")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Regla29Febrero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK_Pais");

                    b.HasIndex("CodigoIso2")
                        .IsUnique()
                        .HasDatabaseName("UQ_Pais_CodigoIso2");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("UQ_Pais_Nombre");

                    b.ToTable("Pais", null, t =>
                        {
                            t.HasCheckConstraint("CK_Pais_RangoEdad", "EdadMinima >= 0 AND EdadMinima <= EdadMaxima");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodigoIso2 = "GT",
                            EdadMaxima = 100,
                            EdadMinima = 18,
                            Nombre = "Guatemala",
                            Regla29Febrero = "VeintiochoDeFebrero"
                        });
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Departamento", b =>
                {
                    b.HasOne("RRHH.Domain.Entidades.Pais", "Pais")
                        .WithMany("Departamentos")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Departamento_Pais");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Empresa", b =>
                {
                    b.HasOne("RRHH.Domain.Entidades.Municipio", "Municipio")
                        .WithMany("Empresas")
                        .HasForeignKey("MunicipioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Empresa_Municipio");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.EmpresaColaborador", b =>
                {
                    b.HasOne("RRHH.Domain.Entidades.Colaborador", "Colaborador")
                        .WithMany("Empresas")
                        .HasForeignKey("ColaboradorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_EmpresaColaborador_Colaborador");

                    b.HasOne("RRHH.Domain.Entidades.Empresa", "Empresa")
                        .WithMany("Colaboradores")
                        .HasForeignKey("EmpresaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_EmpresaColaborador_Empresa");

                    b.Navigation("Colaborador");

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Municipio", b =>
                {
                    b.HasOne("RRHH.Domain.Entidades.Departamento", "Departamento")
                        .WithMany("Municipios")
                        .HasForeignKey("DepartamentoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Municipio_Departamento");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Colaborador", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Departamento", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Empresa", b =>
                {
                    b.Navigation("Colaboradores");
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Municipio", b =>
                {
                    b.Navigation("Empresas");
                });

            modelBuilder.Entity("RRHH.Domain.Entidades.Pais", b =>
                {
                    b.Navigation("Departamentos");
                });
#pragma warning restore 612, 618
        }
    }
}
